services:
  hotech_mysql:
    image: 'mysql:latest'
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: securepassword123
      MYSQL_PASSWORD: securepassword123
      MYSQL_DATABASE: hotech_backend
#    restart: on-failure
#    healthcheck:
#      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
#      timeout: 5s
#      retries: 3